org.bertolinux.qbittorrentapp.QBitDatabase Class Reference
org.bertolinux.qbittorrentapp.QBitDatabase Class Reference
Data Structures
class connectionMetaData
class DbHelper
Public Member Functions
QBitDatabase (Context ctx)
void reset ()
boolean exists ()
String getHostname ()
String getPort ()
String getUsername ()
String getPassword ()
void close ()
void insertConnection (String hostname, String port, String username, String password)
Cursor fetchConnection ()
Package Attributes
SQLiteDatabase mDb
DbHelper mDbHelper
Context mContext
Private Member Functions
void fetch ()
Private Attributes
boolean exists = false
String hostname
String port
String username
String password
Static Private Attributes
static final String DB_NAME ="QBitDatabase.db"
static final int DB_VERSION =1
static final String TABLE_CREATE
Detailed Description
Definition at line 10 of file QBitDatabase.java.
Constructor & Destructor Documentation
QBitDatabase()
org.bertolinux.qbittorrentapp.QBitDatabase.QBitDatabase (Context ctx) inline
Definition at line 24 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.fetch().
Member Function Documentation
close()
void org.bertolinux.qbittorrentapp.QBitDatabase.close () inline
Definition at line 70 of file QBitDatabase.java.
exists()
boolean org.bertolinux.qbittorrentapp.QBitDatabase.exists () inline
Definition at line 49 of file QBitDatabase.java.
fetch()
void org.bertolinux.qbittorrentapp.QBitDatabase.fetch () inline private
Definition at line 35 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.HOSTNAME_KEY, org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.PASSWORD_KEY, org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.PORT_KEY, org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.TABLE, and org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.USERNAME_KEY.
Referenced by org.bertolinux.qbittorrentapp.QBitDatabase.insertConnection(), and org.bertolinux.qbittorrentapp.QBitDatabase.QBitDatabase().
fetchConnection()
Cursor org.bertolinux.qbittorrentapp.QBitDatabase.fetchConnection () inline
Definition at line 84 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.TABLE.
getHostname()
String org.bertolinux.qbittorrentapp.QBitDatabase.getHostname () inline
Definition at line 53 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.hostname.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.init().
getPassword()
String org.bertolinux.qbittorrentapp.QBitDatabase.getPassword () inline
Definition at line 66 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.password.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.init().
getPort()
String org.bertolinux.qbittorrentapp.QBitDatabase.getPort () inline
Definition at line 57 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.port.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.init().
getUsername()
String org.bertolinux.qbittorrentapp.QBitDatabase.getUsername () inline
Definition at line 62 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.username.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.init().
insertConnection()
void org.bertolinux.qbittorrentapp.QBitDatabase.insertConnection (String hostname, String port, String username, String password) inline
Definition at line 74 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.fetch(), org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.HOSTNAME_KEY, org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.PASSWORD_KEY, org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.PORT_KEY, org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.TABLE, and org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.USERNAME_KEY.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.askConnectionData().
reset()
void org.bertolinux.qbittorrentapp.QBitDatabase.reset () inline
Definition at line 31 of file QBitDatabase.java.
References org.bertolinux.qbittorrentapp.QBitDatabase.connectionMetaData.TABLE.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.showTorrents().
Field Documentation
DB_NAME
final String org.bertolinux.qbittorrentapp.QBitDatabase.DB_NAME ="QBitDatabase.db" static private
Definition at line 15 of file QBitDatabase.java.
DB_VERSION
final int org.bertolinux.qbittorrentapp.QBitDatabase.DB_VERSION =1 static private
Definition at line 16 of file QBitDatabase.java.
exists
boolean org.bertolinux.qbittorrentapp.QBitDatabase.exists = false private
Definition at line 17 of file QBitDatabase.java.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.init().
hostname
String org.bertolinux.qbittorrentapp.QBitDatabase.hostname private
Definition at line 19 of file QBitDatabase.java.
Referenced by org.bertolinux.qbittorrentapp.QBitDatabase.getHostname().
mContext
Context org.bertolinux.qbittorrentapp.QBitDatabase.mContext package
Definition at line 14 of file QBitDatabase.java.
mDb
SQLiteDatabase org.bertolinux.qbittorrentapp.QBitDatabase.mDb package
Definition at line 12 of file QBitDatabase.java.
mDbHelper
DbHelper org.bertolinux.qbittorrentapp.QBitDatabase.mDbHelper package
Definition at line 13 of file QBitDatabase.java.
password
String org.bertolinux.qbittorrentapp.QBitDatabase.password private
Definition at line 22 of file QBitDatabase.java.
Referenced by org.bertolinux.qbittorrentapp.QBitDatabase.getPassword().
port
String org.bertolinux.qbittorrentapp.QBitDatabase.port private
Definition at line 20 of file QBitDatabase.java.
Referenced by org.bertolinux.qbittorrentapp.QBitDatabase.getPort().
TABLE_CREATE
final String org.bertolinux.qbittorrentapp.QBitDatabase.TABLE_CREATE static private
Initial value:
= "CREATE TABLE IF NOT EXISTS "
                    + connectionMetaData.TABLE                  + " ("
                    + connectionMetaData.ID                             + " integer primary key autoincrement, "
                    + connectionMetaData.HOSTNAME_KEY   + " text not null, "
                    + connectionMetaData.PORT_KEY               + " integer not null, "
                    + connectionMetaData.USERNAME_KEY   + " text not null, "
                    + connectionMetaData.PASSWORD_KEY   + " text not null);"
Definition at line 97 of file QBitDatabase.java.
username
String org.bertolinux.qbittorrentapp.QBitDatabase.username private
Definition at line 21 of file QBitDatabase.java.
Referenced by org.bertolinux.qbittorrentapp.QBitDatabase.getUsername().
The documentation for this class was generated from the following file:
QBittorrentApp/src/org/bertolinux/qbittorrentapp/QBitDatabase.java