pt.tecnico.phonebook.service.RemovePersonTest Class Reference
pt.tecnico.phonebook.service.RemovePersonTest Class Reference
Public Member Functions
void success ()
void successRemovePersonWithContacts ()
void removeNonexistingPerson ()
Public Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
void setUp () throws Exception
void tearDown ()
Protected Member Functions
void initializeDomain ()
Protected Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
abstract void initializeDomain ()
Private Attributes
Person added
Detailed Description
Definition at line 12 of file RemovePersonTest.java.
Member Function Documentation
initializeDomain()
void pt.tecnico.phonebook.service.RemovePersonTest.initializeDomain () inline protected
Definition at line 16 of file RemovePersonTest.java.
References pt.tecnico.phonebook.domain.PhoneBook.addPerson(), and pt.tecnico.phonebook.domain.PhoneBook.getInstance().
removeNonexistingPerson()
void pt.tecnico.phonebook.service.RemovePersonTest.removeNonexistingPerson () inline
Definition at line 48 of file RemovePersonTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
success()
void pt.tecnico.phonebook.service.RemovePersonTest.success () inline
Definition at line 24 of file RemovePersonTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook(), and pt.tecnico.phonebook.domain.PhoneBook.hasPerson().
successRemovePersonWithContacts()
void pt.tecnico.phonebook.service.RemovePersonTest.successRemovePersonWithContacts () inline
Definition at line 34 of file RemovePersonTest.java.
References pt.tecnico.phonebook.domain.Person.addContact(), pt.tecnico.phonebook.service.PhoneBookService.execute(), pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook(), and pt.tecnico.phonebook.domain.PhoneBook.hasPerson().
Field Documentation
added
Person pt.tecnico.phonebook.service.RemovePersonTest.added private
Definition at line 14 of file RemovePersonTest.java.
The documentation for this class was generated from the following file:
src/test/java/pt/tecnico/phonebook/service/RemovePersonTest.java