pt.tecnico.phonebook.service.PhoneBookService Class Reference
pt.tecnico.phonebook.service.PhoneBookService Class Reference abstract
Public Member Functions
final void execute () throws PhoneBookException
Protected Member Functions
abstract void dispatch () throws PhoneBookException
Static Package Functions
static PhoneBook getPhoneBook ()
static Person getPerson (String personName) throws PersonDoesNotExistException
Detailed Description
Definition at line 12 of file PhoneBookService.java.
Member Function Documentation
dispatch()
abstract void pt.tecnico.phonebook.service.PhoneBookService.dispatch () throws PhoneBookException abstract protected
Referenced by pt.tecnico.phonebook.service.PhoneBookService.execute(), and pt.tecnico.phonebook.service.PhoneBookService.getPerson().
execute()
final void pt.tecnico.phonebook.service.PhoneBookService.execute () throws PhoneBookException inline
Definition at line 15 of file PhoneBookService.java.
References pt.tecnico.phonebook.service.PhoneBookService.dispatch().
Referenced by pt.tecnico.phonebook.service.CreateContactTest.invalidContactCreationWithDuplicateName(), pt.tecnico.phonebook.service.CreateContactTest.invalidContactCreationWithInvalidPhoneNumber(), pt.tecnico.phonebook.service.RemoveContactTest.invalidPerson(), pt.tecnico.phonebook.service.CreateContactTest.invalidPerson(), pt.tecnico.phonebook.service.RemoveContactTest.removeInvalidContact(), pt.tecnico.phonebook.service.RemovePersonTest.removeNonexistingPerson(), pt.tecnico.phonebook.service.CreatePersonTest.success(), pt.tecnico.phonebook.service.RemovePersonTest.success(), pt.tecnico.phonebook.service.RemoveContactTest.success(), pt.tecnico.phonebook.service.CreateContactTest.success(), pt.tecnico.phonebook.service.RemovePersonTest.successRemovePersonWithContacts(), pt.tecnico.phonebook.service.CreateContactTest.successWithPersonWithoutContacts(), and pt.tecnico.phonebook.service.CreatePersonTest.unauthorizedUserCreation().
getPerson()
static Person pt.tecnico.phonebook.service.PhoneBookService.getPerson (String personName) throws PersonDoesNotExistException inline static package
Definition at line 23 of file PhoneBookService.java.
References pt.tecnico.phonebook.service.PhoneBookService.dispatch(), pt.tecnico.phonebook.domain.PhoneBook.getPersonByName(), and pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook().
Referenced by pt.tecnico.phonebook.service.RemovePersonService.dispatch(), pt.tecnico.phonebook.service.RemoveContactService.dispatch(), pt.tecnico.phonebook.service.CreateContactService.dispatch(), and pt.tecnico.phonebook.service.RemoveContactTest.success().
getPhoneBook()
static PhoneBook pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook () inline static package
Definition at line 19 of file PhoneBookService.java.
Referenced by pt.tecnico.phonebook.service.CreatePersonService.dispatch(), pt.tecnico.phonebook.service.RemoveContactTest.getContact(), pt.tecnico.phonebook.service.CreateContactTest.getContact(), pt.tecnico.phonebook.service.PhoneBookService.getPerson(), pt.tecnico.phonebook.service.CreatePersonTest.success(), pt.tecnico.phonebook.service.RemovePersonTest.success(), pt.tecnico.phonebook.service.RemovePersonTest.successRemovePersonWithContacts(), and pt.tecnico.phonebook.service.CreateContactTest.successWithPersonWithoutContacts().
The documentation for this class was generated from the following file:
src/main/java/pt/tecnico/phonebook/service/PhoneBookService.java