pt.tecnico.phonebook.service.CreateContactTest Class Reference
pt.tecnico.phonebook.service.CreateContactTest Class Reference
Public Member Functions
void success ()
void successWithPersonWithoutContacts ()
void invalidContactCreationWithDuplicateName ()
void invalidPerson ()
void invalidContactCreationWithInvalidPhoneNumber ()
Public Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
void setUp () throws Exception
void tearDown ()
Protected Member Functions
void initializeDomain ()
Protected Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
abstract void initializeDomain ()
Private Member Functions
Contact getContact (String personName, String contactName)
Detailed Description
Definition at line 16 of file CreateContactTest.java.
Member Function Documentation
getContact()
Contact pt.tecnico.phonebook.service.CreateContactTest.getContact (String personName, String contactName) inline private
Definition at line 28 of file CreateContactTest.java.
References pt.tecnico.phonebook.domain.Person.getContactByName(), pt.tecnico.phonebook.domain.PhoneBook.getPersonByName(), and pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook().
Referenced by pt.tecnico.phonebook.service.CreateContactTest.success(), and pt.tecnico.phonebook.service.CreateContactTest.successWithPersonWithoutContacts().
initializeDomain()
void pt.tecnico.phonebook.service.CreateContactTest.initializeDomain () inline protected
Definition at line 18 of file CreateContactTest.java.
References pt.tecnico.phonebook.domain.Person.addContact(), pt.tecnico.phonebook.domain.PhoneBook.addPerson(), and pt.tecnico.phonebook.domain.PhoneBook.getInstance().
invalidContactCreationWithDuplicateName()
void pt.tecnico.phonebook.service.CreateContactTest.invalidContactCreationWithDuplicateName () inline
Definition at line 59 of file CreateContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
invalidContactCreationWithInvalidPhoneNumber()
void pt.tecnico.phonebook.service.CreateContactTest.invalidContactCreationWithInvalidPhoneNumber () inline
Definition at line 73 of file CreateContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
invalidPerson()
void pt.tecnico.phonebook.service.CreateContactTest.invalidPerson () inline
Definition at line 66 of file CreateContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
success()
void pt.tecnico.phonebook.service.CreateContactTest.success () inline
Definition at line 34 of file CreateContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), and pt.tecnico.phonebook.service.CreateContactTest.getContact().
successWithPersonWithoutContacts()
void pt.tecnico.phonebook.service.CreateContactTest.successWithPersonWithoutContacts () inline
Definition at line 46 of file CreateContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), pt.tecnico.phonebook.service.CreateContactTest.getContact(), pt.tecnico.phonebook.domain.PhoneBook.getPersonByName(), and pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook().
The documentation for this class was generated from the following file:
src/test/java/pt/tecnico/phonebook/service/CreateContactTest.java