pt.tecnico.phonebook.service.RemoveContactTest Class Reference
pt.tecnico.phonebook.service.RemoveContactTest Class Reference
Public Member Functions
void success ()
void removeInvalidContact ()
void invalidPerson ()
Public Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
void setUp () throws Exception
void tearDown ()
Protected Member Functions
void initializeDomain ()
Protected Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
abstract void initializeDomain ()
Private Member Functions
Contact getContact (String personName, String contactName)
Detailed Description
Definition at line 14 of file RemoveContactTest.java.
Member Function Documentation
getContact()
Contact pt.tecnico.phonebook.service.RemoveContactTest.getContact (String personName, String contactName) inline private
Definition at line 26 of file RemoveContactTest.java.
References pt.tecnico.phonebook.domain.Person.getContactByName(), pt.tecnico.phonebook.domain.PhoneBook.getPersonByName(), and pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook().
Referenced by pt.tecnico.phonebook.service.RemoveContactTest.success().
initializeDomain()
void pt.tecnico.phonebook.service.RemoveContactTest.initializeDomain () inline protected
Definition at line 16 of file RemoveContactTest.java.
References pt.tecnico.phonebook.domain.Person.addContact(), pt.tecnico.phonebook.domain.PhoneBook.addPerson(), and pt.tecnico.phonebook.domain.PhoneBook.getInstance().
invalidPerson()
void pt.tecnico.phonebook.service.RemoveContactTest.invalidPerson () inline
Definition at line 51 of file RemoveContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
removeInvalidContact()
void pt.tecnico.phonebook.service.RemoveContactTest.removeInvalidContact () inline
Definition at line 44 of file RemoveContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
success()
void pt.tecnico.phonebook.service.RemoveContactTest.success () inline
Definition at line 32 of file RemoveContactTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), pt.tecnico.phonebook.service.RemoveContactTest.getContact(), and pt.tecnico.phonebook.service.PhoneBookService.getPerson().
The documentation for this class was generated from the following file:
src/test/java/pt/tecnico/phonebook/service/RemoveContactTest.java