pt.tecnico.phonebook.domain.Contact Class Reference
pt.tecnico.phonebook.domain.Contact Class Reference
Public Member Functions
Contact (String name, Integer phoneNumber) throws InvalidPhoneNumberException
void setPhoneNumber (Integer phoneNumber)
void setPerson (Person person) throws NameAlreadyExistsException
void delete ()
void importFromXML (Element contactElement) throws ImportDocumentException
Element exportToXML ()
Protected Member Functions
Contact ()
Detailed Description
Definition at line 10 of file Contact.java.
Constructor & Destructor Documentation
Contact() [1/2]
pt.tecnico.phonebook.domain.Contact.Contact () inline protected
Definition at line 12 of file Contact.java.
Contact() [2/2]
pt.tecnico.phonebook.domain.Contact.Contact (String name, Integer phoneNumber) throws InvalidPhoneNumberException inline
Definition at line 15 of file Contact.java.
References pt.tecnico.phonebook.domain.Contact.setPhoneNumber().
Member Function Documentation
delete()
void pt.tecnico.phonebook.domain.Contact.delete () inline
Definition at line 38 of file Contact.java.
References pt.tecnico.phonebook.domain.Contact.setPerson().
Referenced by pt.tecnico.phonebook.domain.Person.delete(), and pt.tecnico.phonebook.service.RemoveContactService.dispatch().
exportToXML()
Element pt.tecnico.phonebook.domain.Contact.exportToXML () inline
Definition at line 52 of file Contact.java.
importFromXML()
void pt.tecnico.phonebook.domain.Contact.importFromXML (Element contactElement) throws ImportDocumentException inline
Definition at line 43 of file Contact.java.
References pt.tecnico.phonebook.domain.Contact.setPhoneNumber().
Referenced by pt.tecnico.phonebook.domain.Person.importFromXML().
setPerson()
void pt.tecnico.phonebook.domain.Contact.setPerson (Person person) throws NameAlreadyExistsException inline
Definition at line 29 of file Contact.java.
Referenced by pt.tecnico.phonebook.domain.Contact.delete().
setPhoneNumber()
void pt.tecnico.phonebook.domain.Contact.setPhoneNumber (Integer phoneNumber) inline
Definition at line 21 of file Contact.java.
Referenced by pt.tecnico.phonebook.domain.Contact.Contact(), and pt.tecnico.phonebook.domain.Contact.importFromXML().
The documentation for this class was generated from the following file:
src/main/java/pt/tecnico/phonebook/domain/Contact.java