pt.tecnico.phonebook.service.RemoveContactService Class Reference
pt.tecnico.phonebook.service.RemoveContactService Class Reference
Public Member Functions
RemoveContactService (String personName, String contactName)
final void dispatch () throws ContactDoesNotExistException, PersonDoesNotExistException
Public Member Functions inherited from pt.tecnico.phonebook.service.PhoneBookService
final void execute () throws PhoneBookException
Private Attributes
String personName
String contactName
Additional Inherited Members
Protected Member Functions inherited from pt.tecnico.phonebook.service.PhoneBookService
abstract void dispatch () throws PhoneBookException
Static Package Functions inherited from pt.tecnico.phonebook.service.PhoneBookService
static PhoneBook getPhoneBook ()
static Person getPerson (String personName) throws PersonDoesNotExistException
Detailed Description
Definition at line 10 of file RemoveContactService.java.
Constructor & Destructor Documentation
RemoveContactService()
pt.tecnico.phonebook.service.RemoveContactService.RemoveContactService (String personName, String contactName) inline
Definition at line 15 of file RemoveContactService.java.
References pt.tecnico.phonebook.service.RemoveContactService.contactName, and pt.tecnico.phonebook.service.RemoveContactService.personName.
Member Function Documentation
dispatch()
final void pt.tecnico.phonebook.service.RemoveContactService.dispatch () throws ContactDoesNotExistException, PersonDoesNotExistException inline
Definition at line 20 of file RemoveContactService.java.
References pt.tecnico.phonebook.domain.Contact.delete(), pt.tecnico.phonebook.domain.Person.getContactByName(), and pt.tecnico.phonebook.service.PhoneBookService.getPerson().
Field Documentation
contactName
String pt.tecnico.phonebook.service.RemoveContactService.contactName private
Definition at line 13 of file RemoveContactService.java.
Referenced by pt.tecnico.phonebook.service.RemoveContactService.RemoveContactService().
personName
String pt.tecnico.phonebook.service.RemoveContactService.personName private
Definition at line 12 of file RemoveContactService.java.
Referenced by pt.tecnico.phonebook.service.RemoveContactService.RemoveContactService().
The documentation for this class was generated from the following file:
src/main/java/pt/tecnico/phonebook/service/RemoveContactService.java