pt.tecnico.phonebook.service.ListPeopleService Class Reference
pt.tecnico.phonebook.service.ListPeopleService Class Reference
Public Member Functions
ListPeopleService ()
final void dispatch ()
final List< String > getResult ()
Public Member Functions inherited from pt.tecnico.phonebook.service.PhoneBookService
final void execute () throws PhoneBookException
Private Attributes
List< String > registeredPeople
Additional Inherited Members
Protected Member Functions inherited from pt.tecnico.phonebook.service.PhoneBookService
abstract void dispatch () throws PhoneBookException
Static Package Functions inherited from pt.tecnico.phonebook.service.PhoneBookService
static PhoneBook getPhoneBook ()
static Person getPerson (String personName) throws PersonDoesNotExistException
Detailed Description
Definition at line 11 of file ListPeopleService.java.
Constructor & Destructor Documentation
ListPeopleService()
pt.tecnico.phonebook.service.ListPeopleService.ListPeopleService () inline
Definition at line 15 of file ListPeopleService.java.
Member Function Documentation
dispatch()
final void pt.tecnico.phonebook.service.ListPeopleService.dispatch () inline
Definition at line 18 of file ListPeopleService.java.
References pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook().
getResult()
final List<String> pt.tecnico.phonebook.service.ListPeopleService.getResult () inline
Definition at line 28 of file ListPeopleService.java.
References pt.tecnico.phonebook.service.ListPeopleService.registeredPeople.
Referenced by pt.tecnico.phonebook.PhoneBookApplication.main(), and pt.tecnico.phonebook.PhoneBookApplication.removeAllPeople().
Field Documentation
registeredPeople
List<String> pt.tecnico.phonebook.service.ListPeopleService.registeredPeople private
Definition at line 13 of file ListPeopleService.java.
Referenced by pt.tecnico.phonebook.service.ListPeopleService.getResult().
The documentation for this class was generated from the following file:
src/main/java/pt/tecnico/phonebook/service/ListPeopleService.java