pt.tecnico.phonebook.domain.PhoneBook Class Reference
pt.tecnico.phonebook.domain.PhoneBook Class Reference
Public Member Functions
Person getPersonByName (String name)
boolean hasPerson (String personName)
void addPerson (Person personToBeAdded) throws NameAlreadyExistsException
void importPersonFromXML (Element personElement)
Static Public Member Functions
static PhoneBook getInstance ()
Private Member Functions
PhoneBook ()
Detailed Description
Definition at line 9 of file PhoneBook.java.
Constructor & Destructor Documentation
PhoneBook()
pt.tecnico.phonebook.domain.PhoneBook.PhoneBook () inline private
Definition at line 20 of file PhoneBook.java.
Referenced by pt.tecnico.phonebook.domain.PhoneBook.getInstance().
Member Function Documentation
addPerson()
void pt.tecnico.phonebook.domain.PhoneBook.addPerson (Person personToBeAdded) throws NameAlreadyExistsException inline
Definition at line 38 of file PhoneBook.java.
References pt.tecnico.phonebook.domain.PhoneBook.hasPerson().
Referenced by pt.tecnico.phonebook.service.CreatePersonService.dispatch(), pt.tecnico.phonebook.domain.PhoneBook.importPersonFromXML(), pt.tecnico.phonebook.service.CreatePersonTest.initializeDomain(), pt.tecnico.phonebook.service.RemoveContactTest.initializeDomain(), pt.tecnico.phonebook.service.RemovePersonTest.initializeDomain(), pt.tecnico.phonebook.service.CreateContactTest.initializeDomain(), and pt.tecnico.phonebook.domain.Person.setPhoneBook().
getInstance()
static PhoneBook pt.tecnico.phonebook.domain.PhoneBook.getInstance () inline static
Definition at line 11 of file PhoneBook.java.
References pt.tecnico.phonebook.domain.PhoneBook.PhoneBook().
Referenced by pt.tecnico.phonebook.service.CreatePersonTest.initializeDomain(), pt.tecnico.phonebook.service.RemovePersonTest.initializeDomain(), pt.tecnico.phonebook.service.RemoveContactTest.initializeDomain(), pt.tecnico.phonebook.service.CreateContactTest.initializeDomain(), and pt.tecnico.phonebook.PhoneBookApplication.isInicialized().
getPersonByName()
Person pt.tecnico.phonebook.domain.PhoneBook.getPersonByName (String name) inline
Definition at line 24 of file PhoneBook.java.
Referenced by pt.tecnico.phonebook.service.RemoveContactTest.getContact(), pt.tecnico.phonebook.service.CreateContactTest.getContact(), pt.tecnico.phonebook.service.PhoneBookService.getPerson(), pt.tecnico.phonebook.domain.PhoneBook.hasPerson(), pt.tecnico.phonebook.domain.PhoneBook.importPersonFromXML(), and pt.tecnico.phonebook.service.CreateContactTest.successWithPersonWithoutContacts().
hasPerson()
boolean pt.tecnico.phonebook.domain.PhoneBook.hasPerson (String personName) inline
Definition at line 33 of file PhoneBook.java.
References pt.tecnico.phonebook.domain.PhoneBook.getPersonByName().
Referenced by pt.tecnico.phonebook.domain.PhoneBook.addPerson(), pt.tecnico.phonebook.service.CreatePersonTest.success(), pt.tecnico.phonebook.service.RemovePersonTest.success(), and pt.tecnico.phonebook.service.RemovePersonTest.successRemovePersonWithContacts().
importPersonFromXML()
void pt.tecnico.phonebook.domain.PhoneBook.importPersonFromXML (Element personElement) inline
Definition at line 45 of file PhoneBook.java.
References pt.tecnico.phonebook.domain.PhoneBook.addPerson(), pt.tecnico.phonebook.domain.PhoneBook.getPersonByName(), and pt.tecnico.phonebook.domain.Person.importFromXML().
Referenced by pt.tecnico.phonebook.service.ImportPhoneBookService.dispatch().
The documentation for this class was generated from the following file:
src/main/java/pt/tecnico/phonebook/domain/PhoneBook.java