pt.tecnico.phonebook.PhoneBookApplication Class Reference
pt.tecnico.phonebook.PhoneBookApplication Class Reference
Static Public Member Functions
static void main (String[] args)
static byte [] convertToXML (String personName)
static void printDomainInXML (byte[] doc)
Static Package Functions
static void populateDomain ()
static void removeAllPeople ()
Static Private Member Functions
static void recoverFromBackup (byte[] doc)
static boolean isInicialized ()
static void createPerson (String personName)
static void createContact (String personName, String contactName, int phoneNumber)
Detailed Description
Definition at line 38 of file PhoneBookApplication.java.
Member Function Documentation
convertToXML()
static byte [] pt.tecnico.phonebook.PhoneBookApplication.convertToXML (String personName) inline static
Definition at line 131 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), pt.tecnico.phonebook.exception.PersonDoesNotExistException.getMessage(), and pt.tecnico.phonebook.service.ExportPhoneBookService.getResult().
Referenced by pt.tecnico.phonebook.PhoneBookApplication.main().
createContact()
static void pt.tecnico.phonebook.PhoneBookApplication.createContact (String personName, String contactName, int phoneNumber) inline static private
Definition at line 106 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), and pt.tecnico.phonebook.exception.PersonDoesNotExistException.getMessage().
Referenced by pt.tecnico.phonebook.PhoneBookApplication.populateDomain().
createPerson()
static void pt.tecnico.phonebook.PhoneBookApplication.createPerson (String personName) inline static private
Definition at line 97 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), and pt.tecnico.phonebook.exception.NameAlreadyExistsException.getMessage().
Referenced by pt.tecnico.phonebook.PhoneBookApplication.populateDomain().
isInicialized()
static boolean pt.tecnico.phonebook.PhoneBookApplication.isInicialized () inline static private
Definition at line 92 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.domain.PhoneBook.getInstance().
Referenced by pt.tecnico.phonebook.PhoneBookApplication.populateDomain().
main()
static void pt.tecnico.phonebook.PhoneBookApplication.main (String [] args) inline static
Definition at line 40 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.PhoneBookApplication.convertToXML(), pt.tecnico.phonebook.service.PhoneBookService.execute(), pt.tecnico.phonebook.service.ListPeopleService.getResult(), pt.tecnico.phonebook.service.ListPersonPhoneBook.getResult(), pt.tecnico.phonebook.PhoneBookApplication.populateDomain(), pt.tecnico.phonebook.PhoneBookApplication.printDomainInXML(), pt.tecnico.phonebook.PhoneBookApplication.recoverFromBackup(), and pt.tecnico.phonebook.PhoneBookApplication.removeAllPeople().
populateDomain()
static void pt.tecnico.phonebook.PhoneBookApplication.populateDomain () inline static package
Definition at line 115 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.PhoneBookApplication.createContact(), pt.tecnico.phonebook.PhoneBookApplication.createPerson(), and pt.tecnico.phonebook.PhoneBookApplication.isInicialized().
Referenced by pt.tecnico.phonebook.PhoneBookApplication.main().
printDomainInXML()
static void pt.tecnico.phonebook.PhoneBookApplication.printDomainInXML (byte [] doc) inline static
Definition at line 143 of file PhoneBookApplication.java.
Referenced by pt.tecnico.phonebook.PhoneBookApplication.main().
recoverFromBackup()
static void pt.tecnico.phonebook.PhoneBookApplication.recoverFromBackup (byte [] doc) inline static private
Definition at line 82 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
Referenced by pt.tecnico.phonebook.PhoneBookApplication.main().
removeAllPeople()
static void pt.tecnico.phonebook.PhoneBookApplication.removeAllPeople () inline static package
Definition at line 165 of file PhoneBookApplication.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), and pt.tecnico.phonebook.service.ListPeopleService.getResult().
Referenced by pt.tecnico.phonebook.PhoneBookApplication.main().
The documentation for this class was generated from the following file:
src/main/java/pt/tecnico/phonebook/PhoneBookApplication.java