org.bertolinux.qbittorrentapp.TDownload Class Reference
org.bertolinux.qbittorrentapp.TDownload Class Reference
Public Member Functions
TDownload (JSONObject jsonObject)
String getName ()
String getSize ()
String getProgress ()
String getDlspeed ()
String getEta ()
String getHash ()
String getState ()
Private Attributes
String name
String size
String progress
String dlspeed
String eta
String hash
String state
Detailed Description
Definition at line 5 of file TDownload.java.
Constructor & Destructor Documentation
TDownload()
org.bertolinux.qbittorrentapp.TDownload.TDownload (JSONObject jsonObject) inline
Definition at line 14 of file TDownload.java.
Member Function Documentation
getDlspeed()
String org.bertolinux.qbittorrentapp.TDownload.getDlspeed () inline
Definition at line 39 of file TDownload.java.
References org.bertolinux.qbittorrentapp.TDownload.dlspeed.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
getEta()
String org.bertolinux.qbittorrentapp.TDownload.getEta () inline
Definition at line 43 of file TDownload.java.
References org.bertolinux.qbittorrentapp.TDownload.eta.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
getHash()
String org.bertolinux.qbittorrentapp.TDownload.getHash () inline
Definition at line 47 of file TDownload.java.
References org.bertolinux.qbittorrentapp.TDownload.hash.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
getName()
String org.bertolinux.qbittorrentapp.TDownload.getName () inline
Definition at line 27 of file TDownload.java.
References org.bertolinux.qbittorrentapp.TDownload.name.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
getProgress()
String org.bertolinux.qbittorrentapp.TDownload.getProgress () inline
Definition at line 35 of file TDownload.java.
References org.bertolinux.qbittorrentapp.TDownload.progress.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
getSize()
String org.bertolinux.qbittorrentapp.TDownload.getSize () inline
Definition at line 31 of file TDownload.java.
References org.bertolinux.qbittorrentapp.TDownload.size.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
getState()
String org.bertolinux.qbittorrentapp.TDownload.getState () inline
Definition at line 51 of file TDownload.java.
References org.bertolinux.qbittorrentapp.TDownload.state.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
Field Documentation
dlspeed
String org.bertolinux.qbittorrentapp.TDownload.dlspeed private
Definition at line 9 of file TDownload.java.
Referenced by org.bertolinux.qbittorrentapp.TDownload.getDlspeed().
eta
String org.bertolinux.qbittorrentapp.TDownload.eta private
Definition at line 10 of file TDownload.java.
Referenced by org.bertolinux.qbittorrentapp.TDownload.getEta().
hash
String org.bertolinux.qbittorrentapp.TDownload.hash private
Definition at line 11 of file TDownload.java.
Referenced by org.bertolinux.qbittorrentapp.TDownload.getHash().
name
String org.bertolinux.qbittorrentapp.TDownload.name private
Definition at line 6 of file TDownload.java.
Referenced by org.bertolinux.qbittorrentapp.TDownload.getName().
progress
String org.bertolinux.qbittorrentapp.TDownload.progress private
Definition at line 8 of file TDownload.java.
Referenced by org.bertolinux.qbittorrentapp.TDownload.getProgress().
size
String org.bertolinux.qbittorrentapp.TDownload.size private
Definition at line 7 of file TDownload.java.
Referenced by org.bertolinux.qbittorrentapp.TDownload.getSize().
state
String org.bertolinux.qbittorrentapp.TDownload.state private
Definition at line 12 of file TDownload.java.
Referenced by org.bertolinux.qbittorrentapp.TDownload.getState().
The documentation for this class was generated from the following file:
QBittorrentApp/src/org/bertolinux/qbittorrentapp/TDownload.java