org.bertolinux.qbittorrentapp.GetTorrentList Class Reference
org.bertolinux.qbittorrentapp.GetTorrentList Class Reference
Public Member Functions
GetTorrentList (MainActivity activity)
Protected Member Functions
String doInBackground (Void... arg0)
void onPostExecute (String result)
Private Attributes
MainActivity myactivity
Detailed Description
Definition at line 21 of file GetTorrentList.java.
Constructor & Destructor Documentation
GetTorrentList()
org.bertolinux.qbittorrentapp.GetTorrentList.GetTorrentList (MainActivity activity) inline
Definition at line 24 of file GetTorrentList.java.
Member Function Documentation
doInBackground()
String org.bertolinux.qbittorrentapp.GetTorrentList.doInBackground (Void... arg0) inline protected
Definition at line 29 of file GetTorrentList.java.
References org.bertolinux.qbittorrentapp.MainActivity.getPassword(), org.bertolinux.qbittorrentapp.MainActivity.getUrl(), and org.bertolinux.qbittorrentapp.MainActivity.getUsername().
onPostExecute()
void org.bertolinux.qbittorrentapp.GetTorrentList.onPostExecute (String result) inline protected
Definition at line 64 of file GetTorrentList.java.
References org.bertolinux.qbittorrentapp.MainActivity.manageTorrentList().
Field Documentation
myactivity
MainActivity org.bertolinux.qbittorrentapp.GetTorrentList.myactivity private
Definition at line 22 of file GetTorrentList.java.
The documentation for this class was generated from the following file:
QBittorrentApp/src/org/bertolinux/qbittorrentapp/GetTorrentList.java