org.bertolinux.qbittorrentapp.SendCommand Class Reference
org.bertolinux.qbittorrentapp.SendCommand Class Reference
Public Member Functions
SendCommand (MainActivity activity, String command, String hash, Dialog dialog)
SendCommand (MainActivity activity, String command, String hash, Dialog dialog, boolean newVersion)
void onPostExecute (String result)
Public Member Functions inherited from org.bertolinux.qbittorrentapp.QBitConnection
QBitConnection (MainActivity activity)
void setSpecificUrl (String text)
void setHash (String hash)
Private Attributes
Dialog dialog
Additional Inherited Members
Protected Member Functions inherited from org.bertolinux.qbittorrentapp.QBitConnection
void setNewVersion ()
String doInBackground (QBitConnectionData... connectionData)
Protected Attributes inherited from org.bertolinux.qbittorrentapp.QBitConnection
MainActivity myactivity
File upload
boolean newVersion = false
Detailed Description
Definition at line 5 of file SendCommand.java.
Constructor & Destructor Documentation
SendCommand() [1/2]
org.bertolinux.qbittorrentapp.SendCommand.SendCommand (MainActivity activity, String command, String hash, Dialog dialog) inline
Definition at line 8 of file SendCommand.java.
References org.bertolinux.qbittorrentapp.SendCommand.dialog, org.bertolinux.qbittorrentapp.QBitConnection.setHash(), and org.bertolinux.qbittorrentapp.QBitConnection.setSpecificUrl().
SendCommand() [2/2]
org.bertolinux.qbittorrentapp.SendCommand.SendCommand (MainActivity activity, String command, String hash, Dialog dialog, boolean newVersion) inline
Definition at line 15 of file SendCommand.java.
References org.bertolinux.qbittorrentapp.SendCommand.dialog, org.bertolinux.qbittorrentapp.QBitConnection.hash, and org.bertolinux.qbittorrentapp.QBitConnection.setNewVersion().
Member Function Documentation
onPostExecute()
void org.bertolinux.qbittorrentapp.SendCommand.onPostExecute (String result) inline
Implements org.bertolinux.qbittorrentapp.QBitManagerConnection.
Definition at line 20 of file SendCommand.java.
References org.bertolinux.qbittorrentapp.QBitConnection.myactivity, and org.bertolinux.qbittorrentapp.MainActivity.refreshTorrentList().
Field Documentation
dialog
Dialog org.bertolinux.qbittorrentapp.SendCommand.dialog private
Definition at line 6 of file SendCommand.java.
Referenced by org.bertolinux.qbittorrentapp.SendCommand.SendCommand().
The documentation for this class was generated from the following file:
QBittorrentApp/src/org/bertolinux/qbittorrentapp/SendCommand.java