org.bertolinux.qbittorrentapp.MainActivity Class Reference
org.bertolinux.qbittorrentapp.MainActivity Class Reference
Data Structures
class QBitTimer
Public Member Functions
QBitConnectionData getConnectionData ()
void refreshTorrentList ()
boolean onCreateOptionsMenu (Menu menu)
void manageTorrentList (String json)
void setTotals (String json)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onActivityResult (int requestCode, int resultCode, Intent data)
Private Member Functions
void initIntent ()
void init ()
void askConnectionData ()
void showTorrents ()
Private Attributes
QBitDatabase database
QBitConnectionData connectionData
MainActivity myActivity = this
Static Private Attributes
static final int FILE_SELECT_CODE = 0
static final int PICK_CONTACT_REQUEST = 0
Detailed Description
Definition at line 27 of file MainActivity.java.
Member Function Documentation
askConnectionData()
void org.bertolinux.qbittorrentapp.MainActivity.askConnectionData () inline private
Definition at line 68 of file MainActivity.java.
References org.bertolinux.qbittorrentapp.MainActivity.init(), and org.bertolinux.qbittorrentapp.QBitDatabase.insertConnection().
Referenced by org.bertolinux.qbittorrentapp.MainActivity.init().
getConnectionData()
QBitConnectionData org.bertolinux.qbittorrentapp.MainActivity.getConnectionData () inline
Definition at line 64 of file MainActivity.java.
References org.bertolinux.qbittorrentapp.MainActivity.connectionData.
Referenced by org.bertolinux.qbittorrentapp.QBitAdapter.getView().
init()
void org.bertolinux.qbittorrentapp.MainActivity.init () inline private
Definition at line 56 of file MainActivity.java.
References org.bertolinux.qbittorrentapp.MainActivity.askConnectionData(), org.bertolinux.qbittorrentapp.QBitDatabase.getConnectionData(), and org.bertolinux.qbittorrentapp.MainActivity.showTorrents().
Referenced by org.bertolinux.qbittorrentapp.MainActivity.askConnectionData(), org.bertolinux.qbittorrentapp.MainActivity.onCreate(), and org.bertolinux.qbittorrentapp.MainActivity.showTorrents().
initIntent()
void org.bertolinux.qbittorrentapp.MainActivity.initIntent () inline private
Definition at line 42 of file MainActivity.java.
References org.bertolinux.qbittorrentapp.MainActivity.FILE_SELECT_CODE.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.showTorrents().
manageTorrentList()
void org.bertolinux.qbittorrentapp.MainActivity.manageTorrentList (String json) inline
Definition at line 147 of file MainActivity.java.
Referenced by org.bertolinux.qbittorrentapp.GetTorrentList.onPostExecute().
onActivityResult()
void org.bertolinux.qbittorrentapp.MainActivity.onActivityResult (int requestCode, int resultCode, Intent data) inline protected
Definition at line 185 of file MainActivity.java.
References org.bertolinux.qbittorrentapp.MainActivity.connectionData, and org.bertolinux.qbittorrentapp.MainActivity.PICK_CONTACT_REQUEST.
onCreate()
void org.bertolinux.qbittorrentapp.MainActivity.onCreate (Bundle savedInstanceState) inline protected
Definition at line 35 of file MainActivity.java.
References org.bertolinux.qbittorrentapp.MainActivity.init().
onCreateOptionsMenu()
boolean org.bertolinux.qbittorrentapp.MainActivity.onCreateOptionsMenu (Menu menu) inline
Definition at line 140 of file MainActivity.java.
refreshTorrentList()
void org.bertolinux.qbittorrentapp.MainActivity.refreshTorrentList () inline
Definition at line 90 of file MainActivity.java.
Referenced by org.bertolinux.qbittorrentapp.Upload.onPostExecute(), org.bertolinux.qbittorrentapp.SendCommand.onPostExecute(), org.bertolinux.qbittorrentapp.MainActivity.QBitTimer.run(), and org.bertolinux.qbittorrentapp.MainActivity.showTorrents().
setTotals()
void org.bertolinux.qbittorrentapp.MainActivity.setTotals (String json) inline
Definition at line 161 of file MainActivity.java.
Referenced by org.bertolinux.qbittorrentapp.GetTotals.onPostExecute().
showTorrents()
void org.bertolinux.qbittorrentapp.MainActivity.showTorrents () inline private
Definition at line 95 of file MainActivity.java.
References org.bertolinux.qbittorrentapp.MainActivity.init(), org.bertolinux.qbittorrentapp.MainActivity.initIntent(), org.bertolinux.qbittorrentapp.MainActivity.refreshTorrentList(), and org.bertolinux.qbittorrentapp.QBitDatabase.reset().
Referenced by org.bertolinux.qbittorrentapp.MainActivity.init().
Field Documentation
connectionData
QBitConnectionData org.bertolinux.qbittorrentapp.MainActivity.connectionData private
Definition at line 31 of file MainActivity.java.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.getConnectionData(), and org.bertolinux.qbittorrentapp.MainActivity.onActivityResult().
database
QBitDatabase org.bertolinux.qbittorrentapp.MainActivity.database private
Definition at line 30 of file MainActivity.java.
FILE_SELECT_CODE
final int org.bertolinux.qbittorrentapp.MainActivity.FILE_SELECT_CODE = 0 static private
Definition at line 28 of file MainActivity.java.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.initIntent().
myActivity
MainActivity org.bertolinux.qbittorrentapp.MainActivity.myActivity = this private
Definition at line 32 of file MainActivity.java.
PICK_CONTACT_REQUEST
final int org.bertolinux.qbittorrentapp.MainActivity.PICK_CONTACT_REQUEST = 0 static private
Definition at line 29 of file MainActivity.java.
Referenced by org.bertolinux.qbittorrentapp.MainActivity.onActivityResult().
The documentation for this class was generated from the following file:
QBittorrentApp/src/org/bertolinux/qbittorrentapp/MainActivity.java