org.bertolinux.qbittorrentapp.QBitConnection Class Reference
org.bertolinux.qbittorrentapp.QBitConnection Class Reference abstract
Public Member Functions
QBitConnection (MainActivity activity)
void setSpecificUrl (String text)
void setHash (String hash)
Protected Member Functions
void setNewVersion ()
String doInBackground (QBitConnectionData... connectionData)
Protected Attributes
MainActivity myactivity
File upload
boolean newVersion = false
Private Member Functions
void insertHash (HttpPost job)
void insertUploadFile (HttpPost job)
Private Attributes
String specificUrl
String hash
Detailed Description
Definition at line 31 of file QBitConnection.java.
Constructor & Destructor Documentation
QBitConnection()
org.bertolinux.qbittorrentapp.QBitConnection.QBitConnection (MainActivity activity) inline
Definition at line 39 of file QBitConnection.java.
Member Function Documentation
doInBackground()
String org.bertolinux.qbittorrentapp.QBitConnection.doInBackground (QBitConnectionData... connectionData) inline protected
Definition at line 81 of file QBitConnection.java.
References org.bertolinux.qbittorrentapp.QBitConnection.insertHash(), org.bertolinux.qbittorrentapp.QBitConnection.insertUploadFile(), and org.bertolinux.qbittorrentapp.QBitConnection.specificUrl.
insertHash()
void org.bertolinux.qbittorrentapp.QBitConnection.insertHash (HttpPost job) inline private
Definition at line 55 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.QBitConnection.doInBackground().
insertUploadFile()
void org.bertolinux.qbittorrentapp.QBitConnection.insertUploadFile (HttpPost job) inline private
Definition at line 71 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.QBitConnection.doInBackground().
setHash()
void org.bertolinux.qbittorrentapp.QBitConnection.setHash (String hash) inline
Definition at line 51 of file QBitConnection.java.
References org.bertolinux.qbittorrentapp.QBitConnection.hash.
Referenced by org.bertolinux.qbittorrentapp.SendCommand.SendCommand().
setNewVersion()
void org.bertolinux.qbittorrentapp.QBitConnection.setNewVersion () inline protected
Definition at line 43 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.SendCommand.SendCommand().
setSpecificUrl()
void org.bertolinux.qbittorrentapp.QBitConnection.setSpecificUrl (String text) inline
Definition at line 47 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.GetTorrentList.GetTorrentList(), org.bertolinux.qbittorrentapp.GetTotals.GetTotals(), org.bertolinux.qbittorrentapp.SendCommand.SendCommand(), and org.bertolinux.qbittorrentapp.Upload.Upload().
Field Documentation
hash
String org.bertolinux.qbittorrentapp.QBitConnection.hash private
Definition at line 33 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.SendCommand.SendCommand(), and org.bertolinux.qbittorrentapp.QBitConnection.setHash().
myactivity
MainActivity org.bertolinux.qbittorrentapp.QBitConnection.myactivity protected
Definition at line 35 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.GetTorrentList.onPostExecute(), org.bertolinux.qbittorrentapp.GetTotals.onPostExecute(), org.bertolinux.qbittorrentapp.Upload.onPostExecute(), and org.bertolinux.qbittorrentapp.SendCommand.onPostExecute().
newVersion
boolean org.bertolinux.qbittorrentapp.QBitConnection.newVersion = false protected
Definition at line 37 of file QBitConnection.java.
specificUrl
String org.bertolinux.qbittorrentapp.QBitConnection.specificUrl private
Definition at line 32 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.QBitConnection.doInBackground().
upload
File org.bertolinux.qbittorrentapp.QBitConnection.upload protected
Definition at line 36 of file QBitConnection.java.
Referenced by org.bertolinux.qbittorrentapp.Upload.setUpload().
The documentation for this class was generated from the following file:
QBittorrentApp/src/org/bertolinux/qbittorrentapp/QBitConnection.java