org.bertolinux.qbittorrentapp.QBitAdapter Class Reference
org.bertolinux.qbittorrentapp.QBitAdapter Class Reference
Public Member Functions
QBitAdapter (Context context, int textViewResourceId, List< TDownload > list)
View getView (int position, View convertView, ViewGroup parent)
Protected Attributes
MainActivity myactivity
Detailed Description
Definition at line 17 of file QBitAdapter.java.
Constructor & Destructor Documentation
QBitAdapter()
org.bertolinux.qbittorrentapp.QBitAdapter.QBitAdapter (Context context, int textViewResourceId, List< TDownload > list) inline
Definition at line 20 of file QBitAdapter.java.
Member Function Documentation
getView()
View org.bertolinux.qbittorrentapp.QBitAdapter.getView (int position, View convertView, ViewGroup parent) inline
Definition at line 26 of file QBitAdapter.java.
References org.bertolinux.qbittorrentapp.MainActivity.getConnectionData(), org.bertolinux.qbittorrentapp.TDownload.getDlspeed(), org.bertolinux.qbittorrentapp.TDownload.getEta(), org.bertolinux.qbittorrentapp.TDownload.getHash(), org.bertolinux.qbittorrentapp.TDownload.getName(), org.bertolinux.qbittorrentapp.TDownload.getProgress(), org.bertolinux.qbittorrentapp.TDownload.getSize(), and org.bertolinux.qbittorrentapp.TDownload.getState().
Field Documentation
myactivity
MainActivity org.bertolinux.qbittorrentapp.QBitAdapter.myactivity protected
Definition at line 18 of file QBitAdapter.java.
The documentation for this class was generated from the following file:
QBittorrentApp/src/org/bertolinux/qbittorrentapp/QBitAdapter.java