pt.tecnico.phonebook.domain.Person Class Reference
pt.tecnico.phonebook.domain.Person Class Reference
Public Member Functions
Person (String name)
void setPhoneBook (PhoneBook pb)
void addContact (Contact contactToBeAdded) throws NameAlreadyExistsException
Contact getContactByName (String name)
boolean hasContact (String contactName)
void delete ()
void importFromXML (Element personElement)
Element exportToXML ()
Detailed Description
Definition at line 10 of file Person.java.
Constructor & Destructor Documentation
Person()
pt.tecnico.phonebook.domain.Person.Person (String name) inline
Definition at line 12 of file Person.java.
Member Function Documentation
addContact()
void pt.tecnico.phonebook.domain.Person.addContact (Contact contactToBeAdded) throws NameAlreadyExistsException inline
Definition at line 26 of file Person.java.
References pt.tecnico.phonebook.domain.Person.hasContact().
Referenced by pt.tecnico.phonebook.service.CreateContactService.dispatch(), pt.tecnico.phonebook.domain.Person.importFromXML(), pt.tecnico.phonebook.service.RemoveContactTest.initializeDomain(), pt.tecnico.phonebook.service.CreateContactTest.initializeDomain(), and pt.tecnico.phonebook.service.RemovePersonTest.successRemovePersonWithContacts().
delete()
void pt.tecnico.phonebook.domain.Person.delete () inline
Definition at line 47 of file Person.java.
References pt.tecnico.phonebook.domain.Contact.delete(), and pt.tecnico.phonebook.domain.Person.setPhoneBook().
Referenced by pt.tecnico.phonebook.service.RemovePersonService.dispatch().
exportToXML()
Element pt.tecnico.phonebook.domain.Person.exportToXML () inline
Definition at line 71 of file Person.java.
Referenced by pt.tecnico.phonebook.service.ExportPhoneBookService.dispatch().
getContactByName()
Contact pt.tecnico.phonebook.domain.Person.getContactByName (String name) inline
Definition at line 33 of file Person.java.
Referenced by pt.tecnico.phonebook.service.RemoveContactService.dispatch(), pt.tecnico.phonebook.service.RemoveContactTest.getContact(), pt.tecnico.phonebook.service.CreateContactTest.getContact(), and pt.tecnico.phonebook.domain.Person.hasContact().
hasContact()
boolean pt.tecnico.phonebook.domain.Person.hasContact (String contactName) inline
Definition at line 43 of file Person.java.
References pt.tecnico.phonebook.domain.Person.getContactByName().
Referenced by pt.tecnico.phonebook.domain.Person.addContact().
importFromXML()
void pt.tecnico.phonebook.domain.Person.importFromXML (Element personElement) inline
Definition at line 56 of file Person.java.
References pt.tecnico.phonebook.domain.Person.addContact(), and pt.tecnico.phonebook.domain.Contact.importFromXML().
Referenced by pt.tecnico.phonebook.domain.PhoneBook.importPersonFromXML().
setPhoneBook()
void pt.tecnico.phonebook.domain.Person.setPhoneBook (PhoneBook pb) inline
Definition at line 18 of file Person.java.
References pt.tecnico.phonebook.domain.PhoneBook.addPerson().
Referenced by pt.tecnico.phonebook.domain.Person.delete().
The documentation for this class was generated from the following file:
src/main/java/pt/tecnico/phonebook/domain/Person.java