pt.tecnico.phonebook.service.CreatePersonTest Class Reference
pt.tecnico.phonebook.service.CreatePersonTest Class Reference
Public Member Functions
void success ()
void unauthorizedUserCreation ()
Public Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
void setUp () throws Exception
void tearDown ()
Protected Member Functions
void initializeDomain ()
Protected Member Functions inherited from pt.tecnico.phonebook.service.AbstractServiceTest
abstract void initializeDomain ()
Detailed Description
Definition at line 13 of file CreatePersonTest.java.
Member Function Documentation
initializeDomain()
void pt.tecnico.phonebook.service.CreatePersonTest.initializeDomain () inline protected
Definition at line 15 of file CreatePersonTest.java.
References pt.tecnico.phonebook.domain.PhoneBook.addPerson(), and pt.tecnico.phonebook.domain.PhoneBook.getInstance().
success()
void pt.tecnico.phonebook.service.CreatePersonTest.success () inline
Definition at line 22 of file CreatePersonTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute(), pt.tecnico.phonebook.service.PhoneBookService.getPhoneBook(), and pt.tecnico.phonebook.domain.PhoneBook.hasPerson().
unauthorizedUserCreation()
void pt.tecnico.phonebook.service.CreatePersonTest.unauthorizedUserCreation () inline
Definition at line 32 of file CreatePersonTest.java.
References pt.tecnico.phonebook.service.PhoneBookService.execute().
The documentation for this class was generated from the following file:
src/test/java/pt/tecnico/phonebook/service/CreatePersonTest.java